name: SSM | Dev

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: SSM workflow call
    uses: ./.github/workflows/ssm.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: prod
    secrets: inherit
