# 再利用可能なワークフロー: SSM
name: SSM

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: 対象の環境(dev, stg, prod)

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ASSUME_ROLE_ARN: ${{ secrets.ASSUME_ROLE_ARN }}
  INSTANCE_ID: ${{ secrets.INSTANCE_ID }}

jobs:
  plan:
    name: SSM
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.ASSUME_ROLE_ARN }}

      - name: SSM Send Command
        id: send_command
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ env.INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "echo Hello",
              "echo From",
              "echo Github Actions !"
            ]'
          )
          echo "command_id=$COMMAND_ID" >> $GITHUB_OUTPUT

      - name: SSM Wait Command
        run: aws ssm wait command-executed --command-id ${{ steps.send_command.outputs.command_id }}

      - name: SSM Get Command Result
        run: |
          aws ssm get-command-invocation \
            --instance-id ${{ env.INSTANCE_ID }} \
            --command-id ${{ steps.send_command.outputs.command_id }} \
            --output json \
            --query '{
              status: Status,
              output: StandardOutputContent,
              error: StandardErrorContent
            }'
